version: 0.1

phases:
  install:
    commands:
      - |
        pip install -U pip
        pip install awscli==1.11.177
  pre_build:
    commands:
  build:
    commands:
      - |
        aws cloudformation package \
            --template-file cfn.yml \
            --s3-bucket ${S3_BUCKET} \
            --output-template-file package.yml
  post_build:
    commands:
      - aws s3 cp teststack.yml s3://${S3_BUCKET}/

artifacts:
  files:
    - ./package.yml
  discard-paths: yes