version: 0.1

phases:
  install:
    commands:
      - |
        pip install -U pip
        pip install awscli==1.11.177
  pre_build:
    commands:
      - |
        aws configure set default.region $AWS_DEFAULT_REGION
  build:
    commands:
      - |
        aws cloudformation package \
          --template-file cfn.yml \
          --s3-bucket $S3_BUCKET \
          --output-template-file package.yml
artifacts:
  files:
    - ./package.yml
  discard-paths: yes